name: PR Notifications

on:
  pull_request:
    types:
      - review_requested

jobs:
  notify:
    uses: org-zpr/.github/.github/workflows/pr-review-notify.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }}

